apiVersion: v1
kind: Service
metadata:
  name: govlink-31590764-service
  labels:
    app: govlink-service
spec:
  type: ClusterIP
  selector:
    app: nhic
  ports:
  - protocol: TCP
    name: adminpage
    port: 8889
    targetPort: 8889
  - protocol: TCP
    name: proxyclient
    port: 8890
    targetPort: 8890
  - protocol: TCP
    name: springserver
    port: 8080
    targetPort: 8080