# run
# docker run -p 80:80 -d nginx:1.0.0

# nginx 도커 구축

FROM nginx:1.27.2-alpine

# nginx 설정 파일 변경
COPY ./nginxconfig.conf /etc/nginx/conf.d/nginxconfig.conf

RUN rm /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]